name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: ghvijayakumar
  IMAGE_NAME: myapp
  RESOURCE_GROUP: vijay-Resource-Group
  AKS_CLUSTER_NAME: ghvijayakumar
  K8S_NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Maven project
      run: mvn clean package -DskipTests

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name $ACR_NAME

    - name: Build and push Docker image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

    - name: Deploy app to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml --namespace $K8S_NAMESPACE
        kubectl apply -f k8s/hpa.yaml --namespace $K8S_NAMESPACE
