name: Maven Build & Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Retrieve SSH private key from Key Vault
      id: get-ssh-key
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
        secrets: ssh-private-key

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ steps.get-ssh-key.outputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Azure VM
      run: |
        scp -o StrictHostKeyChecking=no target/*.jar ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:/home/${{ secrets.AZURE_VM_USER }}/app.jar
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} "nohup java -jar app.jar --server.port=8080 > app.log 2>&1 &"
